import type { Metadata } from "next"
import { geistMono, lato } from "@/lib/fontHelper"

import "./globals.css"
import Header from "@/components/layout/Header"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable} ${geistMono.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
